### PR TITLE
updated to angular 19 cli and core

### PR DESCRIPTION
**Pull request by Mehdi-MST**
updated dependecies to angular 19
@angular/cli                       18.1.0 -> 19.0.4         ng update @angular/cli
 @angular/core                      18.1.0 -> 19.0.3         ng update @angular/core

### CODE REVIEW

**Comment by jelledijkstra97** [comment]
+1

**Comment by AlexanderStromer** [comment]
bump

**Review by GeorgeKnap — APPROVED** [review]
looks good

**Comment by miki995** [comment]
I will make an upgrade and publish on Monday.

**Comment by kareldonk** [comment]
@miki995 there is an issue in the current version, trying to open the command palette with the F1 key does not work anymore. It used to work with the Angular 17 version with monaco editor 0.48.0. But since the Angular 18 version with monaco editor 0.50.0 the command palette is empty and the browser console shows the following errors:

image

You can try it in your demo: https://ngx-monaco-editor-v2.surge.sh/
Press F1 in the top editor.

Also why can we not submit issues here on Github?

**Comment by miki995** [comment]
@kareldonk I enabled issues, haven't noticed it so far.

I will fix the issue on v18 first then release it so users won't be stuck on that version.

Then I will upgrade to 19 later today.

**Comment by miki995** [comment]
@kareldonk seems that is the issue in angular itself with zone.js https://github.com/microsoft/monaco-editor/issues/4372

**Comment by kareldonk** [comment]
I am using your package for Angular 18 but forced the monaco dependency to be version 0.44.0. That also works so far. Any version of monaco above 0.44.0 causes the problem. Do you think this is fixable via your package?

**Comment by miki995** [comment]
@kareldonk did you read my last comment or opened the link of the issue?
For some reason angular does remove something from microsoft code, so either microsoft or google solve this, not my package :D

**Comment by kareldonk** [comment]
@miki995 yes I read it, but I was thinking maybe this can be temporarily fixed in your package via a workaround of some kind. If not, then I will have to look for a solution myself.

**Comment by Mehdi-MST** [comment]
hi everyone,
just to let you know this issue is only in development mode as it is asking for Monaco editor inside assets folder. after built you wont get that error. OfCourse you need this configuration  inside angular Json in the build section:

       "assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/monaco-editor",
                "output": "./assets/monaco/"
              }
            ],

kind regards
Mehdi
________________________________

**Comment by ctusch** [comment]
Since the bug is caused by monaco v45 setting its build target to ES2018 which makes it incompatible with Angular's zone.js, I'd argue that ngx-monaco-editor-v2 should stick with monaco v44. What good is an Angular wrapper if the wrapped library does not fully work with the framework?

The only other way this could be resolved is either building monaco yourself with ES6 as target or by going zoneless in your Angular app (but this is still experimental and a lot of work for existing apps).

**Pull request closed without merging**
